### ISSUE TITLE
Suppress loaded resources in shell?

### ISSUE THREAD

**Issue by johnstonian** [sindresorhus/grunt-php#58]
Is there a way to suppress messages generated in the shell for every resource that is loaded? This gets in the way of other messages happening while grunting. Like Sass processing messages, linting output, etc.

**Comment by kevva** [comment]
Are you using this with BrowserSync or what?

**Comment by sindresorhus** [comment]
I've said yes to a `silent` option. PR welcome. https://github.com/sindresorhus/grunt-php/pull/53#issuecomment-71991946

**Comment by kevva** [comment]
Yeah, setting `process.stdout` (or does it write to `stderr`?) to `null` is probably better easier.

**Comment by johnstonian** [comment]
appreciated the work on this! thanks all
