### ISSUE TITLE
KeepAlive: false

### ISSUE THREAD

**Issue by gobsmack** [sindresorhus/grunt-php#60]
I've just started running grunt-php. I had an issue setting up grunt-php with watch. It's probably worth extending the ReadMe example, specifically to say that when you are using "watch", you cannot use "keepalive: true" in the php task.

I'm also having horrible performance serving all files, compared to when I was using PHP through iis-express. Any thoughts on what to look for?

**Comment by NoMan2000** [comment]
If you're running a watch command, how many files total does that watch for?  The larger the amount of changes it has to look for, the slower it will go.
