### ISSUE TITLE
How can I specify which browser should be used with the 'open' parameter?

### ISSUE THREAD

**Issue by goodpixels** [sindresorhus/grunt-php#66]
I want to open the browser of my choice rather than the default system browser when the server starts running. In `grunt-contrib-connect` I am able to do this:

```
connect: {
	
	dev: {
		
		options: {

			keepalive:	false,
			port:		'<%= project.port %>',
			hostname:	'<%= project.hostname %>',
			open:		{

				target: 'http://<%= project.virtualHost %>:<%= project.port %>/<%= project.url %>',
				appName: '<%= project.browser %>'

			}

		}

	}

},
```

Currently my default browser is Safari and the server keeps opening that browser - but I want to launch Google Chrome when server starts instead.

**Comment by kevva** [comment]
It's defined on this line https://github.com/sindresorhus/grunt-php/blob/master/tasks/php.js#L116. By default `opn` will just use the default program. @sindresorhus, think we should add an option for this?

**Comment by sindresorhus** [comment]
Nah, that's an edge case. If you really need this just use `opn` directly instead.

**Comment by goodpixels** [comment]
just out of curiosity: how is that an edge case? we're talking about a plugin for web professionals, not a piece of software for ordinary folk. as a web developer, i use MANY different browsers for testing purposes, and having an optiom to choose what browser should be opened initially is a must. i develop primarily in Chrome, yet my default system browser is Safari, which means that everytime I want to develop a project using your plugin, it will open Safari, then I have to manually close it and open up Chrome instead. that's another extra step that is completely unnecessary. also, stating that your plugin is a 'pretty much drop-in replacement for grunt-contrib-connect' is an overstatement. i think this should be re-opened and reviewed again. this is the sole reason why I feel reluctant to switch to this plugin instead of grunt-contrib-connect.

**Comment by kevva** [comment]
> If you really need this just use `opn` directly instead.

**Comment by goodpixels** [comment]
This doesn't cut it - it should be a configurable option.

**Comment by kevva** [comment]
It's super easy to add:

```js
var grunt = require('grunt');
var opn = require('opn');

grunt.initConfig({
    php: {
        dist: {
            options: {
                port: 5000
            }
        }
    }
});

grunt.registerTask('open', function () {
    opn('http://localhost:5000', 'firefox');
});

grunt.registerTask('default', ['php', 'open']);
```

**Comment by brodkin** [comment]
Alternatively you could also add [grunt-open](https://www.npmjs.com/package/grunt-open) if you're looking for something a little more configuration based.
