### ISSUE TITLE
Couldn't find the PHP binary

### ISSUE THREAD

**Issue by LeG3nDz** [sindresorhus/grunt-php#67]
Hi guys,

I testing this nice grunt module, but when i start "grunt task", i've this message :

    Warning: Couldn't find the `php` binary. Make sure it's installed and in your $PATH Use --force to continue.

All dependency are installed, maybe i need php on my PC ? Can you help me ?

Thank you :)

**Comment by sindresorhus** [comment]
> maybe i need php on my PC ?

Well, yeah. That's exactly what the error message says.

-

Also duplicate of https://github.com/sindresorhus/grunt-php/issues/64. Please try harder next time...
