### ISSUE TITLE
Ability to add environment variables

### ISSUE THREAD

**Issue by brunowego** [sindresorhus/grunt-php#69]
Add environment variables can be of great help. :+1:

**Comment by sindresorhus** [comment]
That's actually already supported https://github.com/sindresorhus/grunt-php/pull/54/files, but it seems we forgot to document it. Fixed now.

https://github.com/sindresorhus/grunt-php#env

**Comment by brunowego** [comment]
Thanks a lot @sindresorhus :+1:
