### ISSUE TITLE
Problem with router.php only when being ran from task

### ISSUE THREAD

**Issue by connelhooley** [sindresorhus/grunt-php#70]
If I run the following command from a terminal in the same directory as my GruntFile.js I can load my wordpress site using the built-in server:

`php -S 127.0.0.1:35729 -t ../../../.. router.php`

However if I run with the following configuration using grunt-php it fails:

```javascript
php: {
	dev: {
		options: {
			hostname: '127.0.0.1',
			port: 35729,
			base: '../../../..',
			router: 'router.php',
			keepalive: false,
			open: true,
		}
	},
},
```
```javascript
grunt.registerTask('default', [
	'php:dev',
	'watch'
]);
```

The error I get is:

> Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0

> Fatal error: Unknown: Failed opening required 'router.php' (include_path='.;C:\xampp\php\PEAR') in Unknown on line 0

Is there anything I need to do differently to get this task to work? I'm trying to run a wordpress site and I'm running Windows.

Thanks

**Comment by sindresorhus** [comment]
Looks it doesn't find the router. Keep in mind that `base` is resolved relatively to the Gruntfile, not the current directory. Run this from the directory of your Gruntfile and make sure the ouput is the path to your router: `$ node -e 'console.log(require("path").resolve("../../../.."))'`.

**Comment by connelhooley** [comment]
I've cd'ed to the GruntFile and ran the command you specified, but it threw an error. I was running it in PowerShell so I tried cmd. On cmd it does not output anything.

```
PS C:\Users\connelhooley> cd .\Documents\Web\connelhooley\wp-content\themes\connelhooley\dev\
PS C:\Users\connelhooley\Documents\Web\connelhooley\wp-content\themes\connelhooley\dev> ls


    Directory: C:\Users\connelhooley\Documents\Web\connelhooley\wp-content\themes\connelhooley\dev


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       07/08/2015     22:11                .sass-cache
d-----       09/08/2015     16:09                dist
d-----       07/08/2015     22:25                node_modules
d-----       09/08/2015     16:09                temp
-a----       08/08/2015     00:57             39 .bowerrc
-a----       07/08/2015     20:22             92 .ftppass
-a----       08/08/2015     00:57             47 .gitignore
-a----       09/08/2015     20:07            696 bower.json
-a----       09/08/2015     20:06           7543 Gruntfile.js
-a----       08/08/2015     00:57            973 package.json
-a----       10/08/2015     10:48             10 router.php


PS C:\Users\connelhooley\Documents\Web\connelhooley\wp-content\themes\connelhooley\dev> node -e 'console.log(require("path").resolve("../../../.."))'

[eval]:1
console.log(require(path).resolve(../../../..))
                                  ^
SyntaxError: Unexpected token .
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3
```

It's worth noting that the router file is kept in the same folder as the GruntFile. Does this task expect the router to be in the base path? The php command looks in the current directory for the router (I ran it from the same directory as the GruntFile) and can find it.

Thanks

**Comment by connelhooley** [comment]
Just got the command to work by escaping the double quotes. Works as expected and returns the path to the WordPress folder I want to serve:
```
PS C:\Users\connelhooley\Documents\Web\connelhooley\wp-content\themes\connelhooley\dev> node -e 'console.log(require(\"path\").resolve(\"../../../..\"))'
C:\Users\connelhooley\Documents\Web\connelhooley
```

**Comment by sindresorhus** [comment]
I have two potential fixes. Can you try them both and let me know if any of them works?

https://github.com/sindresorhus/grunt-php/tree/base-fix
https://github.com/sindresorhus/grunt-php/tree/base-fix2

**Comment by connelhooley** [comment]
I can confirm https://github.com/sindresorhus/grunt-php/commit/b934191d3748624ed74a9a87726ba7573c85d9e4 fixes the issue for me. Sorry about the late reply.

Thanks!

**Comment by thegregthomp** [comment]
I had the same issue and reverted to 1.5.0 and it worked fine. There's something weird with the base & router setting combination with the 1.5.1 fix. My 1.5.0 settings... 

`php: {
            dev: {
                options: {
                    hostname: 'localhost',
                    port: 8889,
                    base: 'cms/public', // Project root
                    keepalive: false,
                    open: false,
                    router:'router.php',
                    env: {
                        DATABASE_HOST: 'localhost',
                        DATABASE_USER: '*',
                        DATABASE_PASS: '*',
                        DATABASE_NAME: '*',
                    }
                }
            }
        },`
