### ISSUE TITLE
how can I set a  variables in *.php

### ISSUE THREAD

**Issue by chenyaoswu** [sindresorhus/grunt-php#74]
HI, I  use grunt-php in my project to run a  php server, but I don't know how to set a variables in *.php? I use <?php echo isset($a) ? $a : '' ?>  to get a value in php , so how can i set it?

**Comment by SamVerschueren** [comment]
Why has this anything to do with `grunt-php`?

If you want environment variables, use the [env](https://github.com/sindresorhus/grunt-php#env) property and use [getenv](http://php.net/manual/en/function.getenv.php) to read them.

**Comment by chenyaoswu** [comment]
Because  I want to use it on a  Existing project, and this project used this grammar。 so I can't use it?

**Comment by SamVerschueren** [comment]
If you need help with PHP, use StackOverflow. This is a [grunt](http://gruntjs.com/) task to start a PHP server, has nothing to do with the language itself.
