### ISSUE TITLE
how to: server config, .htaccess, 404 page file, etc.

### ISSUE THREAD

**Issue by rafegoldberg** [sindresorhus/grunt-php#77]
Noob question I'm sure, but on shared hosting services like BlueHost/GoDaddy/etc. the root directory has a bunch of files `.htaccess`, 404 and other error page files, etc. Wondering if I can use these and how? (Or maybe, alternately, if there's any way to use/access/edit a server config file?)

All I want to do is redirect 404 errors to a php template, which can't be _that_ complex as I figure it!

**Comment by brodkin** [comment]
This project connects with your PC's php-cli and not Apache. As such .htaccess files and such will not work and cannot be modified to work.

**Comment by rafegoldberg** [comment]
gotchya, thanks man!
